### ISSUE TITLE
New Minigame (Ancient Repository hunt)

### ISSUE THREAD

**Issue by mbacookie** [StargateMC/StargateMCPublic#65] opened 2016-06-26 23:03 UTC
The objective of this minigame is to hunt down the Ancient Repository that has been "reported" as being "spotted" on a planet

Reports could either be from a notification when gateing to a planet or have random NPC's on the spawn planets talking about it with a gate address.

Upon gaining the repository it should make you nausious and hungry as well as giving coordinates and an address to an ancient cashe that could contain rare ancient artifacts such as a ZPM or valued material

**Comment by DraksterAU** [comment] 2016-06-26 23:04
Duplicate of #27, but I will use the repository idea for clues :)

**Closed by DraksterAU** 2016-06-26 23:04 UTC
Labels: Duplicate
